### ISSUE TITLE
Auto-packed atlases smaller than 2k x 2k result in render errors

### ISSUE THREAD

**Issue by Tahvohck** [Spacehaven-modding-tools/spacehaven-modloader#2]
With the auto-packer generating .cim atlas files smaller than 2k square, the selection highlight line is too thin. At high resolutions this results in the line completely disappearing.

![](https://cdn.discordapp.com/attachments/593801672422195223/811662306030911598/unknown.png)

Suggested fix: pack all mods into as few 2k x 2k atlases as possible.

**Comment by Tahvohck** [comment]
Despite the bug label, this is technically a bug in the game rather than the modloader.

**Comment by Tahvohck** [comment]
Something to consider: is this actually limited to files smaller than 2k x 2k or will any power of 2 work?

**Comment by Tahvohck** [comment]
Tried to change the code so it uses powers of 2, no luck. Next step would be to use sets of 2k square bins for ALL mods.

**Comment by WalterLPearson** [comment]
Fixed in Prerelease 0.10.0
