### ISSUE TITLE
Possible issue during CIM generation

### ISSUE THREAD

**Issue by Tahvohck** [Spacehaven-modding-tools/spacehaven-modloader#5]
User `icarus_the_improviser` on the Space Haven discord reports issues with cim autogeneration.

![image](https://user-images.githubusercontent.com/1668722/110250441-52988700-7f49-11eb-8782-2460702d1fcc.png)

Issue code section is in `loader/assets/merge.py`:
```python
# cims contains only the textures files that have actually been modified
for page in cims:
    ui.log.log("  Writing {}.cim...".format(page))
    cims[page].export_cim(os.path.join(corePath, 'library', '{}.cim'.format(page)))
    for path in reexport_cims[page]:
        cims[page].export_png(os.path.join(path, 'modded_cim_{}.png'.format(page)))
```

Local testing confirms that the file is generated fine on my machine - this will need more confirmations before I know what to do with it.

**Comment by Brukarnamn** [comment]
I get a similar error with the two following mods. They each work individually if I disable the other. 

PaperFox weapon expansion - https://www.nexusmods.com/spacehaven/mods/33?tab=files
ZeroSystemPoints - https://www.nexusmods.com/spacehaven/mods/20?tab=files

**Comment by Tahvohck** [comment]
I tried to replicate with those two mods only and unfortunately it's not happening on my machine. If you (or anyone else) is able to replicate this while running the code inside of a developer environment, please investigate the `cims` structure for oddities.

**Comment by WalterLPearson** [comment]
I have replicated it.
I got this one.

**Comment by WalterLPearson** [comment]
Right now, merge.py tries to save the file into the textures folder of the last mod it loaded, instead of the mod that has the new textures.
This can be fixed by moving the PNG output from where it is into the texture packing function itself.
I am implementing.

**Comment by Tahvohck** [comment]
Looks like part of the issue is on [line 286 of merge.py](https://github.com/Tahvohck/spacehaven-modloader/blob/0564893482a1e2205955cadf17aed3d9eb9cd4b0/loader/assets/merge.py#L286):
```python
        # write back the cim file as png for debugging
        reexport_cims[page].add(os.path.normpath(mod + "/textures"))
```
That line of code is using the last time `mod` was instantiated, which isn't inside of the same for loop. As of this writing it's further up on line 244.

**Comment by WalterLPearson** [comment]
Yes, I fixed the crash in my last pull request.
I put a per-mod export in, ready to push.  It exports the the packed image for each mod, even if a modder has multiple mods with different textures.  The final cim is left untouched.

**Comment by WalterLPearson** [comment]
Fixed in develop.
